author: Michel Anderson Lutz Teixeira
author_url: https://twitter.com/michel_lutz
github_url: https://github.com/micheltlutz/MLAudioPlayer
root_url: https://micheltlutz.github.io/MLAudioPlayer/
module: MLAudioPlayer
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'MLAudioPlayer.xcworkspace', -scheme, 'MLAudioPlayer-iOS']
